title: Information Companion
author: Asutoaru
email: asutoaru@gmail.com
description:
  References for when judging character and concepts of evil
# social links
twitter_username: feisty_icedtea
github_username:  antheflan
