title: Information Companion
author: An/Asu
email: antheflan@gmail.com
description:
  This is the Information Companion for BPA chapters in planning their attendance at NLC in Orlando, Florida.
  Produced by An and Zhia from Eisenhower Senior High School for the convenience of future users of this Companion!
  Our personal motivations involve providing the most pleasant experience possible on every scholars' trip.
# social links
twitter_username: Antheflan
github_username:  antheflan
